language: cpp
compiler: gcc
dist: focal

addons:
  apt:
    packages: g++ cmake curl python3 python3-pip python3-setuptools make
before_install:
  - pip3 install git+https://github.com/gcovr/gcovr.git
  - cd /tmp
  - wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
  - unzip libtorch-shared-with-deps-latest.zip
  - sudo cp -rv libtorch/* /usr

script:
  - cd $TRAVIS_BUILD_DIR
  - cmake --version
  - ./test.sh
  - echo "{" > coveralls.json
  - "echo \"\\\"service_name\\\": \\\"travis-ci\\\",\" >> coveralls2.json"
  - "echo \"\\\"service_job_id\\\": \\\"$TRAVIS_JOB_ID\\\",\" >> coveralls2.json"
  - tail -c+2 result.json >> coveralls.json
  - cat coveralls.json
  - "curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs"
