language: cpp
compiler: gcc
install: make

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++ cmake curl python3 python3-pip python3-setuptools
before_install:
  - pip3 install git+https://github.com/gcovr/gcovr.git

script:
  - cd $TRAVIS_BUILD_DIR
  - ./test.sh
  - cd build
  - gcovr
  - gcovr --coveralls coveralls.json
  - echo "{" > coveralls2.json
  - "echo \"\\\"service_name\\\": \\\"travis-ci\\\",\" >> coveralls2.json"
  - "echo \"\\\"service_job_id\\\": \\\"$TRAVIS_JOB_ID\\\",\" >> coveralls2.json"
  - tail -c+2 coveralls.json >> coveralls2.json
  - cat coveralls2.json
  - "curl -F 'json_file=@coveralls2.json' https://coveralls.io/api/v1/jobs"
